project:
  output-dir: docs
  type: website

website:
  title: "Lab 6"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    self-contained: true
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

